/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMdiChevronDoubleLeft: typeof import('~icons/mdi/chevron-double-left')['default']
    IMdiChevronDoubleRight: typeof import('~icons/mdi/chevron-double-right')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiTwitch: typeof import('~icons/mdi/twitch')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    NavMenu: typeof import('./src/components/NavMenu/NavMenu.vue')['default']
    ScheduleButton: typeof import('./src/components/ScheduleButton/ScheduleButton.vue')['default']
    TeamGroup: typeof import('./src/components/TeamGroup/TeamGroup.vue')['default']
    TeamGroupsTeam: typeof import('./src/components/TeamGroup/TeamGroupsTeam.vue')['default']
    TeamGroupTeam: typeof import('./src/components/TeamGroup/TeamGroupTeam.vue')['default']
    TeamIcon: typeof import('./src/components/TeamIcon/TeamIcon.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TimeReference: typeof import('./src/components/TimeReference/TimeReference.vue')['default']
    TournamentDay: typeof import('./src/components/TournamentDay/TournamentDay.vue')['default']
    TournamentDayHeader: typeof import('./src/components/TournamentDayHeader/TournamentDayHeader.vue')['default']
    TournamentMatch: typeof import('./src/components/TournamentMatch/TournamentMatch.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
